```{r}
require(tidyverse)
require(foreach)
require(scales)
require(gridExtra)
require(devtools)
require(scales)
devtools::load_all()
```


```{r}
run_sim <- function(iter, N, D, M_total, M_s, M_p, prop_shared, rho, noise, r1, r2, n_cores){
  fix_R =  matrix(c(0, r2, r1, 0), nrow = 2, ncol = 2)
  dataset <- generate_dataset(N = N, D = D, M_total = M_total, M_s = M_s, M_p = M_p, prop_shared = prop_shared, rho = rho, noise = noise, p_net = 0, sd_net = 1, fix_R = fix_R)
  sumstats_select <- dataset$sumstats_select
  sumstats_fit <- dataset$sumstats_fit
  R_cde <- dataset$R_cde
  R_tce <- dataset$R_tce
  beta <- dataset$beta
  
  # First do oracle SNPs and Egger
  mr_method = "egger"
  selected <- select_snps_oracle(beta)
  inst_count <- count_instruments(selected)
  metrics <- instrument_metrics(selected, beta)
  tce_res <- fit_tce(sumstats_fit, selected, mr_method = mr_method)
  
  oracle_res <- tibble(
    iter=iter, mr_method = mr_method, p_thresh = NA, w_thresh = NA, 
    r1_sim = r1, r2_sim = r2, r1 = R_tce[1,2], r2 = R_tce[2, 1],
    r1_hat = tce_res$R_tce[1, 2], r2_hat = tce_res$R_tce[2, 1],
    se1_hat = tce_res$SE_tce[1, 2], se2_hat = tce_res$SE_tce[1, 2],
    p1 = tce_res$p_val[1,2], p2 = tce_res$p_val[2,1],
    n1 = inst_count[1,2][[1]], n2 = inst_count[2,1][[1]])
  
  select_res <- foreach(p_thresh = 0.5*0.1^seq(3, 7), .combine = bind_rows) %do% {
    # Do normal egger.
    selected <- select_snps(sumstats_select, p_thresh = p_thresh, welch_thresh = NULL)
    inst_count <- count_instruments(selected)
    tce_res <- fit_tce(sumstats_fit, selected, mr_method = mr_method)
    normal_res <- tibble(
      iter=iter, mr_method = mr_method, p_thresh = p_thresh, w_thresh = NA, 
      r1_sim = r1, r2_sim = r2, r1 = R_tce[1,2], r2 = R_tce[2, 1],
      r1_hat = tce_res$R_tce[1, 2], r2_hat = tce_res$R_tce[2, 1],
      se1_hat = tce_res$SE_tce[1, 2], se2_hat = tce_res$SE_tce[1, 2],
      p1 = tce_res$p_val[1,2], p2 = tce_res$p_val[2,1],
      n1 = inst_count[1,2][[1]], n2 = inst_count[2,1][[1]])
    
    # Do weighted xor egger.
    selected <- select_snps(sumstats_select, p_thresh = p_thresh, welch_thresh = 0, weight = TRUE)
    inst_count <- count_instruments(selected)
    tce_res <- fit_tce(sumstats_fit, selected, mr_method = "egger_w")
    weight_res <- tibble(
      iter=iter, mr_method =  "egger_w", p_thresh = p_thresh, w_thresh = 0, 
      r1_sim = r1, r2_sim = r2, r1 = R_tce[1,2], r2 = R_tce[2, 1],
      r1_hat = tce_res$R_tce[1, 2], r2_hat = tce_res$R_tce[2, 1],
      se1_hat = tce_res$SE_tce[1, 2], se2_hat = tce_res$SE_tce[1, 2],
      p1 = tce_res$p_val[1,2], p2 = tce_res$p_val[2,1],
      n1 = inst_count[1,2][[1]], n2 = inst_count[2,1][[1]])
    
    return(bind_rows(normal_res, weight_res))
  }
  result <- bind_rows(oracle_res, select_res)
  result <- unite(
    result, "thresh", c("p_thresh", "w_thresh"), sep = "_", remove = FALSE)
  result <- unite(
    result, "method", c("mr_method", "thresh"), sep = "_", remove = FALSE)
  return(result)
}
```


```{r}
# First simulation: NULL, equal sample sizes, unccorrelated pleiotropy.
n_iter = 1000
n_cores = 24
N = 100000
M_s = 1000
M_p = 4000
prop_shared = NULL
M_total = 1000000
D = 2

rho = 0
noise = 0.8 # 20% heritability
r1 = 0 # NULL
r2 = 0
doMC::registerDoMC(cores = n_cores)
plot_tibble_1 = foreach(iter = 1:n_iter, .combine = bind_rows) %dopar% {
  run_sim(iter = iter, N = N, D = D, M_total = M_total, M_s = M_s, M_p = M_p, prop_shared = prop_shared, rho = rho, noise = noise, r1 = r1, r2 = r2)
}
save(plot_tibble_1, file = "~/ukbb_network/plot_data/bimr_sim_1.Rdata")
```


```{r}
# Second simulation: NULL, equal sample sizes, correlated pleiotropy.
n_iter = 1000
N = 100000
n_cores = 24
M_s = 1000
M_p = 4000
prop_shared = NULL
M_total = 1000000
D = 2

rho = 1 # Total genetic correlarion 0.2.
noise = 0.8 # 20% heritability
r1 = 0 # NULL
r2 = 0

plot_tibble_2 = foreach(iter = 1:n_iter, .combine = bind_rows) %dopar% {
  run_sim(iter = iter, N = N, D = D, M_total = M_total, M_s = M_s, M_p = M_p, prop_shared = prop_shared, rho = rho, noise = noise, r1 = r1, r2 = r2)
}
save(plot_tibble_2, file = "~/ukbb_network/plot_data/bimr_sim_2.Rdata")
```


```{r}
# Third simulation: NULL, unequal sample sizes, unequal polygencity correlated pleiotropy.
n_iter = 1000
N = c(200000, 50000)
M_s = 1000
M_p = 4000
prop_shared = c(0.2, 0.333) # Shared SNPs are twice as large as private SNPs in pheno 2.
M_total = 1000000
D = 2

rho = 1 # Total genetic correlarion 0.2.
noise = 0.8 # 20% heritability
r1 = 0 # NULL
r2 = 0

plot_tibble_3 = foreach(iter = 1:n_iter, .combine = bind_rows) %dopar% {
  run_sim(iter = iter, N = N, D = D, M_total = M_total, M_s = M_s, M_p = M_p, prop_shared = prop_shared, rho = rho, noise = noise, r1 = r1, r2 = r2)
}
save(plot_tibble_3, file = "~/ukbb_network/plot_data/bimr_sim_3.Rdata")
```


```{r}
# Fourth simulation: ALT, various values of effect size.
n_iter = 240
n_cores = 24
N = 100000
M_s = 1000
M_p = 4000
prop_shared = NULL
M_total = 1000000
D = 2

rho = 0 # No genetic correlation.
noise = 0.8 # 20% heritability
r1_values <- c(0.05, 0.1, 0.2, 0.31, 0.55, 0.85) # seq(0.05, 0.8, 0.05)
r2 = 0

plot_tibble_4 <- foreach(r1 = r1_values, .combine = bind_rows) %do% {
  foreach(iter = 1:n_iter, .combine = bind_rows) %dopar% {
    run_sim(iter = iter, N = N, D = D, M_total = M_total, M_s = M_s, M_p = M_p, prop_shared = prop_shared, rho = rho, noise = noise, r1 = r1, r2 = r2)
  }
}
save(plot_tibble_4, file = "~/ukbb_network/plot_data/bimr_sim_4.Rdata")
```


```{r}
# Fifth simulation: ALT, various values of effect size, larger sample 1.
n_iter = 240
n_cores = 24
N = c(200000, 50000)
M_s = 1000
M_p = 4000
prop_shared = NULL
M_total = 1000000
D = 2

rho = 0 # No genetic correlation.
noise = 0.8 # 20% heritability
r1_values <-  c(0.05, 0.1, 0.2, 0.31, 0.55, 0.85)
r2 = 0

plot_tibble_5 <- foreach(r1 = r1_values, .combine = bind_rows) %do% {
  foreach(iter = 1:n_iter, .combine = bind_rows) %dopar% {
    run_sim(iter = iter, N = N, D = D, M_total = M_total, M_s = M_s, M_p = M_p, prop_shared = prop_shared, rho = rho, noise = noise, r1 = r1, r2 = r2)
  }
}

save(plot_tibble_5, file = "~/ukbb_network/plot_data/bimr_sim_5.Rdata")
```


```{r}
# Sixth simulation: ALT, various values of effect size, larger sample 2.
n_iter = 240
n_cores = 24
N = c(50000, 200000)
M_s = 1000
M_p = 4000
prop_shared = NULL
M_total = 1000000
D = 2

rho = 0 # No genetic correlation.
noise = 0.8 # 20% heritability
r1_values <- c(0.05, 0.1, 0.2, 0.31, 0.55, 0.85)
r2 = 0

plot_tibble_6 <- foreach(r1 = r1_values, .combine = bind_rows) %do% {
  foreach(iter = 1:n_iter, .combine = bind_rows) %dopar% {
    run_sim(iter = iter, N = N, D = D, M_total = M_total, M_s = M_s, M_p = M_p, prop_shared = prop_shared, rho = rho, noise = noise, r1 = r1, r2 = r2)
  }
}
save(plot_tibble_6, file = "~/ukbb_network/plot_data/bimr_sim_6.Rdata")
```


```{r}
# Seventh simulation: TWO-WAY ALT, various values of effect size, equal sample sizes.
n_iter = 120
N = 100000
M_s = 1000
M_p = 4000
prop_shared = NULL
M_total = 1000000
D = 2

rho = 0 # No genetic correlation.
noise = 0.8 # 20% heritability
r1_values <- c(-0.55, -0.28, -0.1, 0.1, 0.28, 0.55)
r2_values <- c(-0.55, -0.28, -0.1, 0.1, 0.28, 0.55)

plot_tibble_7 <- foreach(r1 = r1_values, .combine = bind_rows) %do% {
  foreach(r2 = r2_values, .combine = bind_rows) %do% {
    foreach(iter = 1:n_iter, .combine = bind_rows) %dopar% {
      run_sim(iter = iter, N = N, D = D, M_total = M_total, M_s = M_s, M_p = M_p, prop_shared = prop_shared, rho = rho, noise = noise, r1 = r1, r2 = r2)
    }
  }
}
save(plot_tibble_7, file = "~/ukbb_network/plot_data/bimr_sim_7.Rdata")
```


```{r}
# Eigth simulation: TWO-WAY ALT, various values of effect size, unequal sample sizes.
n_iter = 120
N = c(200000, 50000)
M_s = 1000
M_p = 4000
prop_shared = NULL
M_total = 1000000
D = 2

rho = 0 # No genetic correlation.
noise = 0.8 # 20% heritability
r1_values <- c(-0.55, -0.28, -0.1, 0.1, 0.28, 0.55)
r2_values <- c(-0.55, -0.28, -0.1, 0.1, 0.28, 0.55)

plot_tibble_8 <- foreach(r1 = r1_values, .combine = bind_rows) %do% {
  foreach(r2 = r2_values, .combine = bind_rows) %do% {
    foreach(iter = 1:n_iter, .combine = bind_rows) %dopar% {
      run_sim(iter = iter, N = N, D = D, M_total = M_total, M_s = M_s, M_p = M_p, prop_shared = prop_shared, rho = rho, noise = noise, r1 = r1, r2 = r2)
    }
  }
}
save(plot_tibble_8, file = "~/ukbb_network/plot_data/bimr_sim_8.Rdata")
```


```{r}
se <- function(x, na.rm = FALSE){
  sqrt(var(x, na.rm = na.rm)/length(x))
}

make_summary_tibble <- function(plot_tibble){
  summary_tibble <- plot_tibble %>% group_by(method, r1_sim, r2_sim) %>% 
    mutate(stat1 = mean(p1 < 0.05, na.rm=T), stat2 = mean(p2 < 0.05, na.rm=T),
           se_stat1 := se(p1 < 0.05, na.rm=T), se_stat2 := se(p2 < 0.05, na.rm=T),
           mae1 = mean(abs(r1 - r1_hat), na.rm=T), mae2 = mean(abs(r2 - r2_hat), na.rm=T),
           se_mae1 = se(abs(r1 - r1_hat), na.rm=T), se_mae2 = se(abs(r2 - r2_hat), na.rm=T),
           r1_hat = mean(r1_hat, na.rm=T), r2_hat = mean(r2_hat, na.rm=T),
           se1_hat = mean(se1_hat, na.rm=T), se2_hat = mean(se2_hat, na.rm=T),
           n1_mean = mean(n1), n2_mean = mean(n2), se_n1 = se(n1), se_n2 = se(n2),
           obs1 = mean(!is.na(r1_hat)), obs2 = mean(!is.na(r2_hat)),
           se_obs1 = se(!is.na(r1_hat)), se_obs2 = se(!is.na(r2_hat)),
           r1 = mean(r1), r2 = mean(r2)) %>% ungroup() %>%
    distinct(method, mr_method, thresh, p_thresh, w_thresh, r1, r2, stat1, stat2,
             se_stat1, se_stat2, mae1, mae2, se_mae1, se_mae2, r1_hat, r2_hat, se1_hat, se2_hat, n1_mean, n2_mean,
             se_n1, se_n2, obs1, obs2, se_obs1, se_obs2, r1_sim, r2_sim)
  return(summary_tibble)
}

reverselog_trans <- function(base = exp(1)) {
    trans <- function(x) -log(x, base)
    inv <- function(x) base^(-x)
    trans_new(paste0("reverselog-", format(base)), trans, inv,
                      log_breaks(base = base), domain = c(1e-100, Inf))
}
```

```{r}
# Load data and make summaries.
# load("~/ukbb_network/plot_data/bimr_sim_1.Rdata")
# load("~/ukbb_network/plot_data/bimr_sim_2.Rdata")
# load("~/ukbb_network/plot_data/bimr_sim_3.Rdata")
# load("~/ukbb_network/plot_data/bimr_sim_4.Rdata")
# load("~/ukbb_network/plot_data/bimr_sim_5.Rdata")
# load("~/ukbb_network/plot_data/bimr_sim_6.Rdata")
load("~/Work/plot_data/bimr_sim_1.Rdata")
load("~/Work/plot_data/bimr_sim_2.Rdata")
load("~/Work/plot_data/bimr_sim_3.Rdata")
load("~/Work/plot_data/bimr_sim_4.Rdata")
load("~/Work/plot_data/bimr_sim_5.Rdata")
load("~/Work/plot_data/bimr_sim_6.Rdata")
load("~/Work/plot_data/bimr_sim_7.Rdata")
load("~/Work/plot_data/bimr_sim_8.Rdata")

summary_tibble_1 <- make_summary_tibble(plot_tibble_1)
summary_tibble_2 <- make_summary_tibble(plot_tibble_2)
summary_tibble_3 <- make_summary_tibble(plot_tibble_3)
summary_tibble_4 <- make_summary_tibble(plot_tibble_4)
summary_tibble_5 <- make_summary_tibble(plot_tibble_5)
summary_tibble_6 <- make_summary_tibble(plot_tibble_6)
summary_tibble_7 <- make_summary_tibble(plot_tibble_7)
summary_tibble_8 <- make_summary_tibble(plot_tibble_8)
```


```{r, fig.width=10}
# Fig 1
p = 5e-06

f1a <- summary_tibble_1 %>% filter((method == "egger_NA_NA")|(method == "egger_5e-08_NA")|(method == paste("egger_w", p, 0, sep = "_"))) %>%
  mutate(Method = c("Oracle", "W-Egger", "Egger")) %>%
  pivot_longer(c(stat1, stat2, se_stat1, se_stat2), names_to = c(".value", "Direction"), names_pattern = "(.*)([1,2])") %>%
  mutate(Direction = if_else(Direction == 1, "P1->P2", "P2->P1")) %>%
  ggplot(aes(Direction, stat, fill = Method)) + 
  geom_errorbar(aes(ymin=stat-se_stat, ymax=stat+se_stat, color = Method), position = "dodge2") + 
  geom_col(position = "dodge2") + 
  labs(x = NULL, y = NULL, title = "a) Null: Uncorrelated pleiotropy") + ylim(0,1) + guides(fill = FALSE, color = FALSE) + theme(plot.title = element_text(size=10))

f1b <- summary_tibble_2 %>% filter((method == "egger_NA_NA")|(method == "egger_5e-08_NA")|(method == paste("egger_w", p, 0, sep = "_"))) %>%
  mutate(Method = c("Oracle", "W-Egger", "Egger")) %>%
  pivot_longer(c(stat1, stat2, se_stat1, se_stat2), names_to = c(".value", "Direction"), names_pattern = "(.*)([1,2])") %>%
  mutate(Direction = if_else(Direction == 1, "P1->P2", "P2->P1")) %>%
  ggplot(aes(Direction, stat, fill = Method)) + 
  geom_errorbar(aes(ymin=stat-se_stat, ymax=stat+se_stat, color = Method), position = "dodge2") + 
  geom_col(position = "dodge2") + 
  labs(x = NULL, y = NULL, title = "b) Null: Correlated pleiotropy")  + ylim(0,1) + guides(fill=FALSE, color = FALSE) + theme(plot.title = element_text(size=10))

f1c <- summary_tibble_3 %>% filter((method == "egger_NA_NA")|(method == "egger_5e-08_NA")|(method == paste("egger_w", p, 0, sep = "_"))) %>%
  mutate(Method = c("Oracle", "W-Egger", "Egger")) %>%
  pivot_longer(c(stat1, stat2, se_stat1, se_stat2), names_to = c(".value", "Direction"), names_pattern = "(.*)([1,2])") %>%
  mutate(Direction = if_else(Direction == 1, "P1->P2", "P2->P1")) %>%
  ggplot(aes(Direction, stat, fill = Method)) + 
  geom_errorbar(aes(ymin=stat-se_stat, ymax=stat+se_stat, color = Method), position = "dodge2") + 
  geom_col(position = "dodge2") + 
  labs(x = NULL, y = NULL, title = "c) Null: Unequal power" ) + ylim(0,1) + theme(plot.title = element_text(size=10))

f1d <- summary_tibble_4 %>% filter((method == "egger_NA_NA")|(method == "egger_5e-08_NA")|(method == paste("egger_w", p, 0, sep = "_"))) %>%
  mutate(Method = rep(c("Oracle", "W-Egger", "Egger"), 6)) %>% 
  pivot_longer(c(stat1, stat2, se_stat1, se_stat2), names_to = c(".value", "Direction"), names_pattern = "(.*)([1,2])") %>%
  mutate(Direction = if_else(Direction == 1, "P1->P2 (Alt)", "P2->P1 (Null)")) %>%
  ggplot(aes(r1, stat, color = Method, linetype = Direction)) + geom_point() + geom_line() + geom_errorbar(aes(ymin=stat-se_stat, ymax=stat+se_stat)) +
  labs(x = NULL, y = NULL, title = "d) One-way alt: Equal sample size")  + ylim(0, 1) + guides(linetype=FALSE, color = FALSE) + theme(plot.title = element_text(size=10))

f1e <- summary_tibble_5 %>% filter((method == "egger_NA_NA")|(method == "egger_5e-08_NA")|(method == paste("egger_w", p, 0, sep = "_"))) %>%
  mutate(Method = rep(c("Oracle", "W-Egger", "Egger"), 6)) %>% 
  pivot_longer(c(stat1, stat2, se_stat1, se_stat2), names_to = c(".value", "Direction"), names_pattern = "(.*)([1,2])") %>%
  mutate(Direction = if_else(Direction == 1, "P1->P2 (Alt)", "P2->P1 (Null)")) %>%
  ggplot(aes(r1, stat, color = Method, linetype = Direction)) + geom_point() + geom_line() + geom_errorbar(aes(ymin=stat-se_stat, ymax=stat+se_stat)) +
  labs(x = NULL, y = NULL, title = "e) One-way alt: Larger sample 1")  + ylim(0, 1) + guides(linetype=FALSE, color = FALSE) + theme(plot.title = element_text(size=10))

f1f <- summary_tibble_6 %>% filter((method == "egger_NA_NA")|(method == "egger_5e-08_NA")|(method == paste("egger_w", p, 0, sep = "_"))) %>%
  mutate(Method = rep(c("Oracle", "W-Egger", "Egger"), 6)) %>% 
  pivot_longer(c(stat1, stat2, se_stat1, se_stat2), names_to = c(".value", "Direction"), names_pattern = "(.*)([1,2])") %>%
  mutate(Direction = if_else(Direction == 1, "P1->P2 (Alt)", "P2->P1 (Null)")) %>%
  ggplot(aes(r1, stat, color = Method, linetype = Direction, )) + geom_point() + geom_line() + geom_errorbar(aes(ymin=stat-se_stat, ymax=stat+se_stat)) +
  labs(x = NULL, y = NULL, title = "f) One-way alt: Larger sample 2") + ylim(0, 1) + guides(color = FALSE) + theme(plot.title = element_text(size=10))

f1 <- ggarrange(f1a, f1b, f1c, f1d, f1e, f1f, ncol = 3, left = "FWER (null) or Power (alt)")
ggsave("~/Work/bimmer/manuscript/figures/figure1.pdf", plot = f1, dpi = 300, width = 10)
```


```{r, fig.width=10}
# Fig 2
r1_val <- c(rep(-0.5, 12), rep(-0.25, 12), rep(-0.1, 12), rep(0.1, 12), rep(0.25, 12), rep(0.5, 12))
r2_val <- rep(c(-0.5, -0.5, -0.25, -0.25, -0.1, -0.1, 0.1, 0.1, 0.25, 0.25, 0.5, 0.5), 6)

f2a <- summary_tibble_7 %>% filter(method == paste("egger_w", p, 0, sep = "_") | method == "egger_5e-08_NA") %>%
  mutate(r1_val = fct_reorder(as.character(r1_val), r1_val), r2_val = fct_reorder(as.character(r2_val), r2_val)) %>%
  mutate(Method = rep(c("W-Egger", "Egger"), 36)) %>%
  ggplot(aes(r1_val, r2_val)) + geom_tile(aes(fill = stat1)) + scale_fill_gradient(limits = c(0, 1)) + facet_wrap(~ Method, ncol = 2) +
  labs(x = NULL, y = NULL, title = "a) Equal sample sizes, P1->P2") + guides(fill = FALSE) + theme(plot.title = element_text(size=10))

f2b <- summary_tibble_7 %>% filter(method == paste("egger_w", p, 0, sep = "_") | method == "egger_5e-08_NA") %>%
  mutate(r1_val = fct_reorder(as.character(r1_val), r1_val), r2_val = fct_reorder(as.character(r2_val), r2_val)) %>%
  mutate(Method = rep(c("W-Egger", "Egger"), 36)) %>%
  ggplot(aes(r1_val, r2_val)) + geom_tile(aes(fill = stat2)) + scale_fill_gradient(limits = c(0, 1), name = "Power") + facet_wrap(~ Method, ncol = 2) +
  labs(x = NULL, y = NULL, title = "b) Equal sample sizes, P2->P1")  + theme(plot.title = element_text(size=10))

f2c <- summary_tibble_8 %>% filter(method == paste("egger_w", p, 0, sep = "_") | method == "egger_5e-08_NA") %>%
  mutate(r1_val = fct_reorder(as.character(r1_val), r1_val), r2_val = fct_reorder(as.character(r2_val), r2_val)) %>%
  mutate(Method = rep(c("W-Egger", "Egger"), 36)) %>%
  ggplot(aes(r1_val, r2_val)) + geom_tile(aes(fill = stat1)) + scale_fill_gradient(limits = c(0, 1)) + facet_wrap(~ Method, ncol = 2) +
  labs(x = NULL, y = NULL, title = "c) Larger sample 1, P1->P2") + guides(fill = FALSE) + theme(plot.title = element_text(size=10))

f2d <- summary_tibble_8 %>% filter(method == paste("egger_w", p, 0, sep = "_") | method == "egger_5e-08_NA") %>%
  mutate(r1_val = fct_reorder(as.character(r1_val), r1_val), r2_val = fct_reorder(as.character(r2_val), r2_val)) %>%
  mutate(Method = rep(c("W-Egger", "Egger"), 36)) %>%
  ggplot(aes(r1_val, r2_val)) + geom_tile(aes(fill = stat2)) + scale_fill_gradient(limits = c(0, 1)) + facet_wrap(~ Method, ncol = 2) +
  labs(x = NULL, y = NULL, title = "d) Larger sample 1, P2->P1") + guides(fill = FALSE) + theme(plot.title = element_text(size=10))

f2 <- ggarrange(f2a, f2b, f2c, f2d, ncol = 2, widths = c(1.05, 1))
ggsave("~/Work/bimmer/manuscript/figures/figure2.pdf", plot = f2, dpi = 300, width = 10)
```


```{r}
t1 <- summary_tibble_1 %>% filter((method == "egger_NA_NA")|(method == "egger_5e-08_NA")|(method == paste("egger_w", p, 0, sep = "_"))) %>%
  mutate(Method = c("Oracle", "W-Egger", "Egger")) %>%
  mutate(stat1 = round(stat1, 3), se_stat1 = round(se_stat1, 3), stat2 = round(stat2, 3), se_stat2 = round(se_stat2, 3)) %>%
  mutate(mae1 = round(mae1, 3), se_mae1 = round(se_mae1, 3), mae2 = round(mae2, 3), se_mae2 = round(se_mae2, 3)) %>%
  select(Method, stat1, se_stat1, stat2, se_stat2, mae1, se_mae1, mae2, se_mae2)

t2 <- summary_tibble_2 %>% filter((method == "egger_NA_NA")|(method == "egger_5e-08_NA")|(method == paste("egger_w", p, 0, sep = "_"))) %>%
  mutate(Method = c("Oracle", "W-Egger", "Egger")) %>% 
  mutate(stat1 = round(stat1, 3), se_stat1 = round(se_stat1, 3), stat2 = round(stat2, 3), se_stat2 = round(se_stat2, 3)) %>%
  mutate(mae1 = round(mae1, 3), se_mae1 = round(se_mae1, 3), mae2 = round(mae2, 3), se_mae2 = round(se_mae2, 3)) %>%
  select(Method, stat1, se_stat1, stat2, se_stat2, mae1, se_mae1, mae2, se_mae2)

t3 <- summary_tibble_3 %>% filter((method == "egger_NA_NA")|(method == "egger_5e-08_NA")|(method == paste("egger_w", p, 0, sep = "_"))) %>%
  mutate(Method = c("Oracle", "W-Egger", "Egger")) %>%
  mutate(stat1 = round(stat1, 3), se_stat1 = round(se_stat1, 3), stat2 = round(stat2, 3), se_stat2 = round(se_stat2, 3)) %>%
  mutate(mae1 = round(mae1, 3), se_mae1 = round(se_mae1, 3), mae2 = round(mae2, 3), se_mae2 = round(se_mae2, 3)) %>%
  select(Method, stat1, se_stat1, stat2, se_stat2, mae1, se_mae1, mae2, se_mae2)

t4 <- summary_tibble_4 %>% filter((method == "egger_NA_NA")|(method == "egger_5e-08_NA")|(method == paste("egger_w", p, 0, sep = "_"))) %>%
  filter(r1_sim == 0.2) %>%
  mutate(Method = c("Oracle", "W-Egger", "Egger")) %>% 
  mutate(stat1 = round(stat1, 3), se_stat1 = round(se_stat1, 3), stat2 = round(stat2, 3), se_stat2 = round(se_stat2, 3)) %>%
  mutate(mae1 = round(mae1, 3), se_mae1 = round(se_mae1, 3), mae2 = round(mae2, 3), se_mae2 = round(se_mae2, 3)) %>%
  select(Method, stat1, se_stat1, stat2, se_stat2, mae1, se_mae1, mae2, se_mae2)

t5 <- summary_tibble_4 %>% filter((method == "egger_NA_NA")|(method == "egger_5e-08_NA")|(method == paste("egger_w", p, 0, sep = "_"))) %>%
  filter(r1_sim == 0.55) %>%
  mutate(Method = c("Oracle", "W-Egger", "Egger")) %>%
  mutate(stat1 = round(stat1, 3), se_stat1 = round(se_stat1, 3), stat2 = round(stat2, 3), se_stat2 = round(se_stat2, 3)) %>%
  mutate(mae1 = round(mae1, 3), se_mae1 = round(se_mae1, 3), mae2 = round(mae2, 3), se_mae2 = round(se_mae2, 3)) %>%
  select(Method, stat1, se_stat1, stat2, se_stat2, mae1, se_mae1, mae2, se_mae2)

t6 <- summary_tibble_5 %>% filter((method == "egger_NA_NA")|(method == "egger_5e-08_NA")|(method == paste("egger_w", p, 0, sep = "_"))) %>%
  filter(r1_sim == 0.2) %>%
  mutate(Method = c("Oracle", "W-Egger", "Egger")) %>% 
  mutate(stat1 = round(stat1, 3), se_stat1 = round(se_stat1, 3), stat2 = round(stat2, 3), se_stat2 = round(se_stat2, 3)) %>%
  mutate(mae1 = round(mae1, 3), se_mae1 = round(se_mae1, 3), mae2 = round(mae2, 3), se_mae2 = round(se_mae2, 3)) %>%
  select(Method, stat1, se_stat1, stat2, se_stat2, mae1, se_mae1, mae2, se_mae2)

t7 <- summary_tibble_5 %>% filter((method == "egger_NA_NA")|(method == "egger_5e-08_NA")|(method == paste("egger_w", p, 0, sep = "_"))) %>%
  filter(r1_sim == 0.55) %>%
  mutate(Method = c("Oracle", "W-Egger", "Egger")) %>% 
  mutate(stat1 = round(stat1, 3), se_stat1 = round(se_stat1, 3), stat2 = round(stat2, 3), se_stat2 = round(se_stat2, 3)) %>%
  mutate(mae1 = round(mae1, 3), se_mae1 = round(se_mae1, 3), mae2 = round(mae2, 3), se_mae2 = round(se_mae2, 3)) %>%
  select(Method, stat1, se_stat1, stat2, se_stat2, mae1, se_mae1, mae2, se_mae2)

t8 <- summary_tibble_6 %>% filter((method == "egger_NA_NA")|(method == "egger_5e-08_NA")|(method == paste("egger_w", p, 0, sep = "_"))) %>%
  filter(r1_sim == 0.2) %>%
  mutate(Method = c("Oracle", "W-Egger", "Egger")) %>% 
  mutate(stat1 = round(stat1, 3), se_stat1 = round(se_stat1, 3), stat2 = round(stat2, 3), se_stat2 = round(se_stat2, 3)) %>%
  mutate(mae1 = round(mae1, 3), se_mae1 = round(se_mae1, 3), mae2 = round(mae2, 3), se_mae2 = round(se_mae2, 3)) %>%
  select(Method, stat1, se_stat1, stat2, se_stat2, mae1, se_mae1, mae2, se_mae2)

t9 <- summary_tibble_6 %>% filter((method == "egger_NA_NA")|(method == "egger_5e-08_NA")|(method == paste("egger_w", p, 0, sep = "_"))) %>%
  filter(r1_sim == 0.55) %>%
  mutate(Method = c("Oracle", "W-Egger", "Egger")) %>% 
  mutate(stat1 = round(stat1, 3), se_stat1 = round(se_stat1, 3), stat2 = round(stat2, 3), se_stat2 = round(se_stat2, 3)) %>%
  mutate(mae1 = round(mae1, 3), se_mae1 = round(se_mae1, 3), mae2 = round(mae2, 3), se_mae2 = round(se_mae2, 3)) %>%
  select(Method, stat1, se_stat1, stat2, se_stat2, mae1, se_mae1, mae2, se_mae2)

table1 <- rbind(t1, t2, t3)
table2 <- rbind(t4, t5, t6, t7, t8, t9)

kable1 <- kable(table1, "latex", booktabs = T) %>% 
  kable_styling(position ="center", latex_options = "scale_down") %>%
  pack_rows("Null: Uncorrelated pleiotropy", 1, 3) %>%
  pack_rows("Null: Correlated pleiotropy", 4, 6) %>%
  pack_rows("Null: Correlated pleiotropy, unequal power", 7, 9)

kable2 <- kable(table2, "latex", booktabs = T) %>% 
  kable_styling(position ="center", latex_options = "scale_down") %>%
  pack_rows("Alt: Equal sample sizes, R=0.2", 1, 3) %>%
  pack_rows("Alt: Equal sample sizes, R=0.5", 4, 6) %>%
  pack_rows("Alt: Larger sample 1, R=0.2", 7, 9) %>%
  pack_rows("Alt: Larger sample 1, R=0.5", 10, 12) %>%
  pack_rows("Alt: Larger sample 2, R=0.2", 13, 15) %>%
  pack_rows("Alt: Larger sample 2, R=0.5", 16, 18)
```


```{r}
s1 <- summary_tibble_1 %>% filter(mr_method == "egger_w") %>% mutate(Method = "W-Egger") %>%
  mutate(stat1 = round(stat1, 3), se_stat1 = round(se_stat1, 3), stat2 = round(stat2, 3), se_stat2 = round(se_stat2, 3)) %>%
  mutate(mae1 = round(mae1, 3), se_mae1 = round(se_mae1, 3), mae2 = round(mae2, 3), se_mae2 = round(se_mae2, 3), p_thresh = as.character(p_thresh)) %>%
  select(p_thresh, stat1, se_stat1, stat2, se_stat2, mae1, se_mae1, mae2, se_mae2)

s2 <- summary_tibble_2 %>% filter(mr_method == "egger_w") %>% mutate(Method = "W-Egger") %>%
  mutate(stat1 = round(stat1, 3), se_stat1 = round(se_stat1, 3), stat2 = round(stat2, 3), se_stat2 = round(se_stat2, 3)) %>%
  mutate(mae1 = round(mae1, 3), se_mae1 = round(se_mae1, 3), mae2 = round(mae2, 3), se_mae2 = round(se_mae2, 3), p_thresh = as.character(p_thresh)) %>%
  select(p_thresh, stat1, se_stat1, stat2, se_stat2, mae1, se_mae1, mae2, se_mae2)

s3 <- summary_tibble_3 %>% filter(mr_method == "egger_w") %>% mutate(Method = "W-Egger") %>%
  mutate(stat1 = round(stat1, 3), se_stat1 = round(se_stat1, 3), stat2 = round(stat2, 3), se_stat2 = round(se_stat2, 3)) %>%
  mutate(mae1 = round(mae1, 3), se_mae1 = round(se_mae1, 3), mae2 = round(mae2, 3), se_mae2 = round(se_mae2, 3), p_thresh = as.character(p_thresh)) %>%
  select(p_thresh, stat1, se_stat1, stat2, se_stat2, mae1, se_mae1, mae2, se_mae2)

s4 <- summary_tibble_4 %>% filter(mr_method == "egger_w") %>% mutate(Method = "W-Egger") %>%
  filter(r1_sim == 0.2) %>%
  mutate(stat1 = round(stat1, 3), se_stat1 = round(se_stat1, 3), stat2 = round(stat2, 3), se_stat2 = round(se_stat2, 3)) %>%
  mutate(mae1 = round(mae1, 3), se_mae1 = round(se_mae1, 3), mae2 = round(mae2, 3), se_mae2 = round(se_mae2, 3), p_thresh = as.character(p_thresh)) %>%
  select(p_thresh, stat1, se_stat1, stat2, se_stat2, mae1, se_mae1, mae2, se_mae2)

s5 <- summary_tibble_4 %>% filter(mr_method == "egger_w") %>% mutate(Method = "W-Egger") %>%
  filter(r1_sim == 0.55) %>%
  mutate(stat1 = round(stat1, 3), se_stat1 = round(se_stat1, 3), stat2 = round(stat2, 3), se_stat2 = round(se_stat2, 3)) %>%
  mutate(mae1 = round(mae1, 3), se_mae1 = round(se_mae1, 3), mae2 = round(mae2, 3), se_mae2 = round(se_mae2, 3), p_thresh = as.character(p_thresh)) %>%
  select(p_thresh, stat1, se_stat1, stat2, se_stat2, mae1, se_mae1, mae2, se_mae2)

s6 <- summary_tibble_5 %>% filter(mr_method == "egger_w") %>% mutate(Method = "W-Egger") %>%
  filter(r1_sim == 0.2) %>%
  mutate(stat1 = round(stat1, 3), se_stat1 = round(se_stat1, 3), stat2 = round(stat2, 3), se_stat2 = round(se_stat2, 3)) %>%
  mutate(mae1 = round(mae1, 3), se_mae1 = round(se_mae1, 3), mae2 = round(mae2, 3), se_mae2 = round(se_mae2, 3), p_thresh = as.character(p_thresh)) %>%
  select(p_thresh, stat1, se_stat1, stat2, se_stat2, mae1, se_mae1, mae2, se_mae2)

s7 <- summary_tibble_5 %>% filter(mr_method == "egger_w") %>% mutate(Method = "W-Egger") %>%
  filter(r1_sim == 0.55) %>%
  mutate(stat1 = round(stat1, 3), se_stat1 = round(se_stat1, 3), stat2 = round(stat2, 3), se_stat2 = round(se_stat2, 3)) %>%
  mutate(mae1 = round(mae1, 3), se_mae1 = round(se_mae1, 3), mae2 = round(mae2, 3), se_mae2 = round(se_mae2, 3), p_thresh = as.character(p_thresh)) %>%
  select(p_thresh, stat1, se_stat1, stat2, se_stat2, mae1, se_mae1, mae2, se_mae2)

s8 <- summary_tibble_6 %>% filter(mr_method == "egger_w") %>% mutate(Method = "W-Egger") %>%
  filter(r1_sim == 0.2) %>%
  mutate(stat1 = round(stat1, 3), se_stat1 = round(se_stat1, 3), stat2 = round(stat2, 3), se_stat2 = round(se_stat2, 3)) %>%
  mutate(mae1 = round(mae1, 3), se_mae1 = round(se_mae1, 3), mae2 = round(mae2, 3), se_mae2 = round(se_mae2, 3), p_thresh = as.character(p_thresh)) %>%
  select(p_thresh, stat1, se_stat1, stat2, se_stat2, mae1, se_mae1, mae2, se_mae2)

s9 <- summary_tibble_6 %>% filter(mr_method == "egger_w") %>% mutate(Method = "W-Egger") %>%
  filter(r1_sim == 0.55) %>%
  mutate(stat1 = round(stat1, 3), se_stat1 = round(se_stat1, 3), stat2 = round(stat2, 3), se_stat2 = round(se_stat2, 3)) %>%
  mutate(mae1 = round(mae1, 3), se_mae1 = round(se_mae1, 3), mae2 = round(mae2, 3), se_mae2 = round(se_mae2, 3), p_thresh = as.character(p_thresh)) %>%
  select(p_thresh, stat1, se_stat1, stat2, se_stat2, mae1, se_mae1, mae2, se_mae2)

table_s1 <- rbind(s1, s2, s3)
table_s2 <- rbind(s4, s5, s6, s7, s8, s9)

kable_s1 <- kable(table_s1, "latex", booktabs = T) %>% 
  kable_styling(position ="center", latex_options = "scale_down") %>%
  pack_rows("Null: Uncorrelated pleiotropy", 1, 5) %>%
  pack_rows("Null: Correlated pleiotropy", 6, 10) %>%
  pack_rows("Null: Correlated pleiotropy, unequal power", 11, 15)

kable_s2 <- kable(table_s2, "latex", booktabs = T) %>% 
  kable_styling(position ="center", latex_options = "scale_down") %>%
  pack_rows("Alt: Equal sample sizes, R=0.2", 1, 5) %>%
  pack_rows("Alt: Equal sample sizes, R=0.5", 6, 10) %>%
  pack_rows("Alt: Larger sample 1, R=0.2", 11, 15) %>%
  pack_rows("Alt: Larger sample 1, R=0.5", 16, 20) %>%
  pack_rows("Alt: Larger sample 2, R=0.2", 21, 25) %>%
  pack_rows("Alt: Larger sample 2, R=0.5", 26, 30)
```
